### ISSUE TITLE
[PROBLEM STATEMENT] [DEVELOPMENT PLAN] Address Feedback

### ISSUE THREAD

**Issue by Sevhena** [ssm-lab/capstone--source-code-optimizer#263]
# Important Notes!!

When making changes to documentation, we need to keep track of the changes we make. You've probably noticed in the sample documents we've referenced that they have red text to show their changes. This is a rubric component. We could do that but we could also make it simpler and remove the need for red text in our documents. If you follow exactly the steps listed below we can just use version control to track our changes!!

- Make sure to reference the issue in the commits. Each commit should have changes related to a single issue
- When you make changes, make note of them in the revision table at the beginning of the document
- If the feedback mentioned in the issue will not be fixed, need to explain why before closing issue (important, again rubric component)

p.s. if you forget to link the number of the issue (but please don't) then just copy the SHA id of the commit and paste it as a comment in the issue the commit is for. That will manually create a link between the commit and the issue.

The branching strategy will be 1 branch per document. A PR will be merged once all issues in the epic (this one) are addressed. You can view the branch name below or in the **Development** section in the sidebar.

**branch name for this epic:** `prob-dev-feedback`

I've attached pictures of the feedback from the rubric, but feel free to check the feedback on avenue if more context is needed.

# Feedback

- [x] #255
- [x] #264
- [x] #265
- [x] #266
- [x] #267

**Comment by Sevhena** [comment]
# Feedback

- [ ] TA Feedback - (Prob) Consider adding goal for generating a detailed energy report
- [ ] TA Feedback - (Dev) Define more concrete team member roles
- [ ] TA Feedback - (Dev) Fix any quotation marks
- [ ] TA Feedback - (Dev) Refine Team Charter
- [ ] TA Feedback - (Dev) Clearly Identify Risks in POC Plan
