### ISSUE TITLE
[DELIVERABLE 1] Problem Statement Document

### ISSUE THREAD

**Issue by Sevhena** [ssm-lab/capstone--source-code-optimizer#7]
## Tasks to complete:

**Note**: *Tasks not assigned to anyone are to be done by everyone*

- [x] Problem (@mmyaaaaa )
- [x] Input/Outputs (@Ayushi1972 )
- [x] Stakeholders (@Sevhena  )
- [x] Environment (@Ayushi1972 )
- [x] Goals (@tbrar06)
- [x] Stretch Goals (@tbrar06)
- [x] Challenge Level & Extras (@nivethakuruparan)
- [x] Reflections (@mmyaaaaa @Ayushi1972 @Sevhena @tbrar06 @nivethakuruparan)

**File**: [Problem Statement Document](https://github.com/Sevhena/capstone--source-code-optimizer/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf)
